"""Generate bounded 4-bit Noto Sans glyphs in flash for the portable renderer."""
from pathlib import Path
import argparse
from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
ROLES = [('Small', 15, 400), ('Meta', 16, 400), ('Heading', 18, 700), ('Title', 22, 700), ('Clock', 41, 700)]
CHARS = sorted(set(range(32, 127)) | set(range(160, 256)) | {0x2013, 0x2014, 0x2018, 0x2019, 0x201c, 0x201d, 0x2026})

def generate(output: Path):
    lines = ['// Generated by firmware/tools/generate_fonts.py; Noto Sans, SIL OFL 1.1.', '#include "SceneCore.h"', '#ifdef ARDUINO', '#include <pgmspace.h>', '#else', '#define PROGMEM', '#endif', 'namespace scene {']
    for name, size, weight in ROLES:
        face = ImageFont.truetype(str(ROOT / 'assets/NotoSans.ttf'), size)
        axes = face.get_variation_axes()
        face.set_variation_by_axes([weight if axis['name'] == b'Weight' else axis['default'] for axis in axes])
        chars = [32, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 63] if name == 'Clock' else CHARS
        baseline = -face.getbbox('Hg', anchor='ls')[1]
        data, glyphs, bottom = [], [], 0
        for code in chars:
            char = chr(code)
            x, y, right, low = face.getbbox(char, anchor='ls')
            w, h = right-x, low-y
            canvas = Image.new('L', (max(1,w), max(1,h)))
            ImageDraw.Draw(canvas).text((-x,-y), char, font=face, fill=255, anchor='ls')
            levels = [(pixel*15+127)//255 for pixel in canvas.getdata()] if w*h else []
            offset = len(data)
            assert offset < 65536 and baseline+y >= -8
            data.extend((levels[i]<<4) | (levels[i+1] if i+1<len(levels) else 0) for i in range(0,len(levels),2))
            glyphs.append(f'{{{offset},{code},{w},{h},{round(face.getlength(char))},{x},{y}}}')
            bottom = max(bottom, baseline+low)
        lines.append(f'static const uint8_t data{name}[] PROGMEM = {{')
        lines.extend(','.join(str(v) for v in data[i:i+32])+',' for i in range(0,len(data),32))
        lines.extend(['};', f'static const Glyph glyphs{name}[] PROGMEM = {{', ',\n'.join(glyphs), '};', f'static const Font font{name} = {{data{name},glyphs{name},{len(chars)},{baseline},{bottom}}};'])
        print(f'{name}: {len(chars)} glyphs, {len(data)} bitmap bytes, height {bottom}')
    lines.append('const Font& font(FontId id) { switch(id) {')
    lines.extend(f'case FontId::{name}: return font{name};' for name,_,_ in ROLES)
    lines.extend(['default: return fontSmall; } }', '} // namespace scene'])
    output.write_text('\n'.join(lines)+'\n', encoding='utf-8')

if __name__ == '__main__':
    parser=argparse.ArgumentParser()
    parser.add_argument('output', type=Path)
    generate(parser.parse_args().output)
