"""Embed corrected management pages in firmware; OTA does not replace LittleFS."""
from pathlib import Path
import gzip
import re

ROOT=Path(__file__).resolve().parents[1]
FILES={'wifi.html':'text/html','token.html':'text/html','logs.html':'text/html','update.html':'text/html','js/utils.js':'application/javascript',
       'js/wifiHandler.js':'application/javascript','js/tokenHandler.js':'application/javascript',
       'js/logsHandler.js':'application/javascript','js/otaUploadHandler.js':'application/javascript'}

def generate():
    lines=['// Generated by tools/generate_web.py; gzip assets live in flash.',
           '#include <Arduino.h>', '#include "web/Webserver.h"', '#include "web/EmbeddedWeb.h"']
    for index,name in enumerate(FILES):
        raw=(ROOT/'data/web'/name).read_bytes()
        if name.endswith('.html'):
            raw=re.sub(rb'(\./js/(?:utils|wifiHandler|tokenHandler|logsHandler|otaUploadHandler)\.js)"', rb'\1?v=wifi3"', raw)
        zipped=gzip.compress(raw,compresslevel=9,mtime=0)
        lines.append(f'static const uint8_t asset{index}[] PROGMEM={{')
        lines.extend(','.join(str(v) for v in zipped[i:i+32])+',' for i in range(0,len(zipped),32))
        lines.append('};')
        print(name,len(raw),'->',len(zipped),'bytes')
    lines.append('void registerEmbeddedWeb(Webserver* server) {')
    for index,(name,mime) in enumerate(FILES.items()):
        for prefix in ('/','/web/'):
            lines.extend([f' server->raw().on("{prefix}{name}",HTTP_GET,[server]() {{',
                          '  server->raw().sendHeader("Content-Encoding","gzip");',
                          '  server->raw().sendHeader("Cache-Control","no-store");',
                          f'  server->raw().send_P(200,"{mime}",reinterpret_cast<PGM_P>(asset{index}),sizeof(asset{index}));', ' });'])
    lines.append('}')
    (ROOT/'src/web/EmbeddedWeb.cpp').write_text('\n'.join(lines)+'\n',encoding='utf-8')

if __name__=='__main__': generate()
